# Generated by Django 3.0.3 on 2020-05-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='nummeroIdentidad',
            new_name='numeroIdentidad',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nota',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroTelefono',
            field=models.IntegerField(),
        ),
    ]
